ALTER TABLE tigers DROP COLUMN created_by;
ALTER TABLE tigers ADD last_seen TIMESTAMP NOT NULL;
ALTER TABLE tigers ADD lat DOUBLE PRECISION NOT NULL;
ALTER TABLE tigers ADD lng DOUBLE PRECISION NOT NULL;