// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/signup.go
//
// Generated by this command:
//
//	mockgen -source=./service/signup.go -destination=./mocks/mock_signup.go -package=mocks github.com/pranoyk/tiger-sightings/service SignUpUser
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	custom_err "github.com/pranoyk/tiger-sightings/custom-err"
	model "github.com/pranoyk/tiger-sightings/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSignUpUser is a mock of SignUpUser interface.
type MockSignUpUser struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpUserMockRecorder
}

// MockSignUpUserMockRecorder is the mock recorder for MockSignUpUser.
type MockSignUpUserMockRecorder struct {
	mock *MockSignUpUser
}

// NewMockSignUpUser creates a new mock instance.
func NewMockSignUpUser(ctrl *gomock.Controller) *MockSignUpUser {
	mock := &MockSignUpUser{ctrl: ctrl}
	mock.recorder = &MockSignUpUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpUser) EXPECT() *MockSignUpUserMockRecorder {
	return m.recorder
}

// SignUp mocks base method.
func (m *MockSignUpUser) SignUp(user *model.SignUpUserRequest) (string, *custom_err.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*custom_err.APIError)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockSignUpUserMockRecorder) SignUp(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockSignUpUser)(nil).SignUp), user)
}
